### ISSUE TITLE
`zh-TW` is an unsupported culture code

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu-localisation-analyser#44]
We're currently pulling culture codes from the osu-web [directory listing](https://github.com/ppy/osu-web/tree/master/resources/lang).

`zh-tw` is one of them, and the only one which looks to be unsupported by .NET. This particular localisation does not generate a `zh-tw` directory in the output path:
![image](https://user-images.githubusercontent.com/1329837/162851996-96397368-14f4-45ca-94a0-0576e5ef8390.png)

I don't know exactly how this is currently working in osu!/from where it's managing to pull the string resources, but it causes issues such as:
- The culture appears in JetBrains Rider's Localization Manager as its own entity:
  ![image](https://user-images.githubusercontent.com/1329837/162852192-bcaa65ea-3f74-4ff9-b2c3-b4a742418fd5.png)
- External rulesets can't include the `zh-TW` localisation (see: https://github.com/karaoke-dev/karaoke/pull/1266)

Other projects, notably [Humanizer](https://github.com/Humanizr/Humanizer/tree/main/NuSpecs) and [dotnet-roslyn](https://github.com/dotnet/roslyn/tree/main/src/Analyzers/CSharp/CodeFixes/xlf) use `zh-Hans` and `zh-Hant` in place of our `zh` and `zh-TW` locales respectively.

I can't really find any documentation on the supported culture codes - the closest I can find is documentation related to Bing maps which lists `zh-Hans` and `zh-Hant`: https://docs.microsoft.com/en-us/bingmaps/rest-services/common-parameters-and-types/supported-culture-codes, however we should be reasonably able to trust that JetBrains Rider's visualisation is accurate and that zh-TW is the only one which is unsupported.

**Comment by andy840119** [comment]
`zh-TW` Means it's a language related to the country, and `zh`, `zh-Hans` and `zh-Hant` means it's just a language.
Like the relationship between `ja-JP` and `ja`.
Not really sure it will ba another reason to change `zh`,  `zh-TW`  into `zh-Hans` and `zh-Hant`
.
But the weird things is that compile `osu.Desktop` generated `zh-TW` (And it works on lazer also)
![image](https://user-images.githubusercontent.com/9100368/162854817-d05c7b06-cc0c-4c87-ab8c-2ee665703a02.png)

**Comment by smoogipoo** [comment]
> But the weird things is that compile `osu.Desktop` generated `zh-TW` (And it works on lazer also)

Aha. So that must be why lazer's working.

Weirdly, compiling osu.Game.Resources locally doesn't generate zh-TW but it's included in the Nuget.org nupkg? The only thing I can come up with is that `osu-resources` is packaged on Windows whereas neither of us are using it.

**Comment by andy840119** [comment]
I think it might be a suitable way.

BTW, i'm curious about will `osu-web` follow the same roles?

Also, not really sure language in `osu-web` is more related with country(Because it have country flag? Or is that a language flag?)
So will use something like `ja-JP` is more suitable than `ja`?
![image](https://user-images.githubusercontent.com/9100368/162868610-0dcc15ea-4756-4b19-a871-8a5a33c8f4db.png)

**Comment by smoogipoo** [comment]
I'm unsure what to do with osu-web and crowdin for that matter.

Initially I was thinking this could be a osu-localisation-analyser tool-specific thing, maybe a CLI option for converting `zh-TW` to `zh-Hant`, in order to avoid having to change crowdin + coordinate with peppy's private scripts that I don't have access to.

**Comment by smoogipoo** [comment]
For the time being, let's wait and see if .NET SDK 6.0.300 fixes the issue. It looks to be on their radar in some fashion:
https://github.com/dotnet/msbuild/issues/7331#issuecomment-1024291531

**Comment by bdach** [comment]
Not sure how to interpret the linked chain of pulls above in the context of waiting for SDK 6.0.300. Are these changes to be reviewed now, or are they just PR'd for visibility and to be reviewed later if upstream doesn't include a workaround on their side?

**Comment by smoogipoo** [comment]
They can be reviewed. At the end of the day I think whatever the SDK does is going to be considered a "hack" as this seems to have been an intentional change.
